from dotenv import load_dotenv
import os

load_dotenv(override=True, verbose=True)

# POSTGRESQL DATABASE
_POSTGRES_DB = os.getenv("POSTGRES_DB")
_POSTGRES_HOST = os.getenv("POSTGRES_HOST")
_POSTGRES_PORT = os.getenv("POSTGRES_PORT")
_POSTGRES_USERNAME = os.getenv("POSTGRES_USERNAME")
_POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
_DB_TYPE = os.getenv("DB_TYPE")
assert _POSTGRES_DB
assert _POSTGRES_HOST
assert _POSTGRES_PORT
assert _POSTGRES_USERNAME
assert _POSTGRES_PASSWORD
assert _DB_TYPE
POSTGRES_DB = _POSTGRES_DB
POSTGRES_HOST = _POSTGRES_HOST
POSTGRES_PORT = _POSTGRES_PORT
POSTGRES_USERNAME = _POSTGRES_USERNAME
POSTGRES_PASSWORD = _POSTGRES_PASSWORD
DB_TYPE = _DB_TYPE

# GAMMA DATABASE
_GAMMA_DB = os.getenv("GAMMA_DB")
_GAMMA_HOST = os.getenv("GAMMA_HOST")
_GAMMA_PORT = os.getenv("GAMMA_PORT")
_GAMMA_USERNAME = os.getenv("GAMMA_USERNAME")
_GAMMA_PASSWORD = os.getenv("GAMMA_PASSWORD")
_GAMMA_DB_TYPE = os.getenv("GAMMA_DB_TYPE")
assert _GAMMA_DB
assert _GAMMA_HOST
assert _GAMMA_PORT
assert _GAMMA_USERNAME
assert _GAMMA_PASSWORD
assert _GAMMA_DB_TYPE
GAMMA_DB = _GAMMA_DB
GAMMA_HOST = _GAMMA_HOST
GAMMA_PORT = _GAMMA_PORT
GAMMA_USERNAME = _GAMMA_USERNAME
GAMMA_PASSWORD = _GAMMA_PASSWORD
GAMMA_DB_TYPE = _GAMMA_DB_TYPE