table _MEASURES
	lineageTag: e6d63244-f352-4117-867b-65c24970d5af

	/// CALCULATE(COUNT(SESSIONS[session_id]))
	measure SESSIONS = CALCULATE(COUNT(SESSIONS[session_id]))
		formatString: #,0
		displayFolder: KPI \ SESSIONS
		lineageTag: 8b3bfe80-ac6a-4e59-a61c-2b71173dd7d4
		dataCategory: true

	/// DIVIDE([MINUTES WATCHED],[STREAMING SESSIONS],BLANK())
	measure 'MINUTES WATCHED - AVG' = DIVIDE([MINUTES WATCHED],[STREAMING SESSIONS],BLANK())
		formatString: 0
		displayFolder: KPI \ SESSIONS \ EPISODES
		lineageTag: bd856541-4f3c-42bc-9056-becb82d7ffb3
		dataCategory: true

	/// CALCULATE(SUM(STREAMING[watched_minutes]))
	measure 'MINUTES WATCHED' = CALCULATE(SUM(STREAMING[watched_minutes]))
		formatString: 0
		displayFolder: KPI \ SESSIONS \ EPISODES
		lineageTag: 3a292571-bafa-4bd8-91ae-94fba1dc5523
		dataCategory: true

	/// [STREAMING SESSIONS]*[SESSIONS]
	measure 'SESSIONS KPI' = [STREAMING SESSIONS]*[SESSIONS]
		formatString: #,0
		displayFolder: KPI \ SESSIONS \ STREAMING
		lineageTag: bc80bbd8-3cb3-475c-999e-3193224e53a1
		dataCategory: true

	/// CALCULATE(COUNT(SESSIONS[session_id]),SESSIONS[episodes_in_session]>0)
	measure 'STREAMING SESSIONS' = CALCULATE(COUNT(SESSIONS[session_id]),SESSIONS[episodes_in_session]>0)
		formatString: #,0
		displayFolder: KPI \ SESSIONS \ STREAMING
		lineageTag: f9d8923c-b9fa-4bc5-9e1e-25710ad677b7
		dataCategory: true

	/// 0.9
	measure 'STREAMING SESSIONS - TARGET' = 0.9
		formatString: 0 %;-0 %;0 %
		displayFolder: KPI \ SESSIONS \ STREAMING
		lineageTag: 7b264503-af5b-47ca-a3be-bad35d9cca35
		dataCategory: true

	/// DIVIDE([STREAMING SESSIONS],[SESSIONS],1)
	measure 'STREAMING SESSIONS PERC' = DIVIDE([STREAMING SESSIONS],[SESSIONS],1)
		formatString: 0 %;-0 %;0 %
		displayFolder: KPI \ SESSIONS \ STREAMING
		lineageTag: f5e6b5f6-9cfe-436e-a19e-9fc829d35f90
		dataCategory: true

	/// DIVIDE([EPISODES WATCHED],[STREAMING SESSIONS],0)
	measure 'EPISODES WATCHED PR. SESSION' = DIVIDE([EPISODES WATCHED],[STREAMING SESSIONS],0)
		formatString: 0
		displayFolder: KPI \ SESSIONS \ EPISODES
		lineageTag: 27667301-842f-4409-8037-3a2366d063d3
		dataCategory: true

	/// DIVIDE([EPISODES WATCHED TO END],[EPISODES WATCHED],1)
	measure 'EPISODES WATCHED TO END PERC' = DIVIDE([EPISODES WATCHED TO END],[EPISODES WATCHED],1)
		formatString: 0 %;-0 %;0 %
		displayFolder: KPI \ SESSIONS \ EPISODES
		lineageTag: d99e2a56-789f-497d-a2ca-37127a789f56
		dataCategory: true

	/// CALCULATE(COUNT(STREAMING[episode_id]),STREAMING[finished])
	measure 'EPISODES WATCHED TO END' = CALCULATE(COUNT(STREAMING[episode_id]),STREAMING[finished])
		formatString: #,0
		displayFolder: KPI \ SESSIONS \ EPISODES
		lineageTag: fafbb214-9548-4c36-bd56-4eb54b5c1677
		dataCategory: true

	/// CALCULATE(COUNT(STREAMING[episode_id]))
	measure 'EPISODES WATCHED' = CALCULATE(COUNT(STREAMING[episode_id]))
		formatString: #,0
		displayFolder: KPI \ SESSIONS \ EPISODES
		lineageTag: efea0cfd-26e8-4e03-81ac-dffee8456efc
		dataCategory: true

	/// CALCULATE(DISTINCTCOUNT(SESSIONS[user_id]))
	measure USERS = CALCULATE(DISTINCTCOUNT(SESSIONS[user_id]))
		formatString: #,0
		displayFolder: KPI \ USERS
		lineageTag: 3e59116a-db0c-4f50-aa40-2d4f4ca379e3
		dataCategory: true

	/// CALCULATE(DISTINCTCOUNT(SESSIONS[user_id]))
	measure 'ACTIVE USERS' = CALCULATE(DISTINCTCOUNT(SESSIONS[user_id]))
		formatString: #,0
		displayFolder: KPI \ USERS
		lineageTag: d3ccba78-bb48-443e-8e66-dd6492cd82c0
		dataCategory: true

	/// DIVIDE([ACTIVE USERS],[USERS],1)
	measure 'ACTIVE USERS PERC' = DIVIDE([ACTIVE USERS],[USERS],1)
		formatString: 0 %;-0 %;0 %
		displayFolder: KPI \ USERS
		lineageTag: 5be9b507-5930-4532-89e8-4a1aec100c17
		dataCategory: true

	/// SELECTEDVALUE(PROGRAMS[image])
	measure 'PROGRAM IMAGE' = SELECTEDVALUE(PROGRAMS[image])
		displayFolder: VISUALS \ URL IMG
		lineageTag: fb9ee41c-7c5c-4d66-9397-502c85a4d4f7
		dataCategory: ImageUrl

	/// 
	/// VAR TotalMinutes = CALCULATE(SUM(STREAMING[watched_minutes]))
	/// VAR Days = INT(DIVIDE(TotalMinutes, 1440))                // 1440 min = 1 day
	/// VAR Hours = INT(DIVIDE(MOD(TotalMinutes, 1440), 60))      // Remaining hours
	/// VAR Minutes = MOD(TotalMinutes, 60)                       // Remaining minutes
	/// RETURN
	/// SWITCH(
	/// TRUE(),
	/// Days > 0,
	/// FORMAT(Days, "00") & " d. " & FORMAT(Hours, "00") & " t." & FORMAT(Minutes, "00") & " m." ,
	/// Hours > 0,
	/// FORMAT(Hours, "00") & " t." & FORMAT(Minutes, "00") & " m.",
	/// FORMAT(Minutes, "00") & " m."
	/// )
	measure 'WATCHED TIME FORMATTED' = ```
			
			VAR TotalMinutes = CALCULATE(SUM(STREAMING[watched_minutes]))
			VAR Days = INT(DIVIDE(TotalMinutes, 1440))                // 1440 min = 1 day
			VAR Hours = INT(DIVIDE(MOD(TotalMinutes, 1440), 60))      // Remaining hours
			VAR Minutes = MOD(TotalMinutes, 60)                       // Remaining minutes
			RETURN
			SWITCH(
			    TRUE(),
			    Days > 0, 
			        FORMAT(Days, "00") & " d. " & FORMAT(Hours, "00") & " t." & FORMAT(Minutes, "00") & " m." ,
			    Hours > 0, 
			        FORMAT(Hours, "00") & " t." & FORMAT(Minutes, "00") & " m.",
			    FORMAT(Minutes, "00") & " m."
			)
			```
		displayFolder: VISUALS \ TEXT
		lineageTag: 88da804b-8181-4acb-a3b2-3fee4198548a
		dataCategory: true

	column Column
		isHidden
		formatString: 0
		lineageTag: c3e79820-f40d-4234-aed5-2bc139b7c253
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _MEASURES = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 31c8b286f65740b38be9097d373e4811

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

