table '_MEASURES - CUSTOM'
	lineageTag: 77e58648-0c0e-4199-b086-2a18e9e15663

	/// CALCULATE(SUM('GAMMA - POSTERINGER'[amount]))
	measure REALISERET = CALCULATE(SUM('GAMMA - POSTERINGER'[amount]))
		formatString: #,0\ "kr.";-#,0\ "kr.";#,0\ "kr."
		displayFolder: KPI \ REALISERET
		lineageTag: bf002f70-dc4b-4a06-93c6-73c76ca7f087
		dataCategory: true

	/// VAR BelongsToLastYear = SELECTEDVALUE('GAMMA - POSTERINGER'[belongs_to_last_year], FALSE)
	/// RETURN
	/// IF (
	///     NOT BelongsToLastYear,
	///     CALCULATE(
	///         [REALISERET],
	///         SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
	///     ) +
	///     CALCULATE(
	///         [REALISERET],
	///         'GAMMA - POSTERINGER'[belongs_to_last_year] = TRUE
	///     ),
	///     CALCULATE(
	///         [REALISERET],
	///         SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
	///     )
	/// )
	measure 'REALISERET - SPLY' =
			VAR BelongsToLastYear = SELECTEDVALUE('GAMMA - POSTERINGER'[belongs_to_last_year], FALSE)
			RETURN
			IF (
			    NOT BelongsToLastYear,
			    CALCULATE(
			        [REALISERET],
			        SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
			    ) +
			    CALCULATE(
			        [REALISERET],
			        'GAMMA - POSTERINGER'[belongs_to_last_year] = TRUE
			    ),
			    CALCULATE(
			        [REALISERET],
			        SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
			    )
			)
		formatString: #,0\ "kr.";-#,0\ "kr.";#,0\ "kr."
		displayFolder: KPI \ REALISERET
		lineageTag: 47b7f4e0-e6da-4008-8029-4c7d8b6d1fd2
		dataCategory: true

	/// CALCULATE(SUM('GAMMA - FORECAST'[forecast]))
	measure FORECAST = CALCULATE(SUM('GAMMA - FORECAST'[forecast]))
		formatString: #,0\ "kr.";-#,0\ "kr.";#,0\ "kr."
		displayFolder: KPI \ FC
		lineageTag: 2ad0efbc-b64a-441a-a940-54b6595a9f2c
		dataCategory: true

	/// CALCULATE([FORECAST],'GAMMA - FORECAST'[forecast_type] <> "BU")
	measure 'FORECAST - NOT BU' = CALCULATE([FORECAST],'GAMMA - FORECAST'[forecast_type] <> "BU")
		formatString: #,0\ "kr.";-#,0\ "kr.";#,0\ "kr."
		displayFolder: KPI \ FC
		lineageTag: 4704eb95-9fbd-4415-aa96-1c0ca8061535
		dataCategory: true

	/// CALCULATE (
	///     DISTINCTCOUNTNOBLANK ( 'GAMMA - POSTERINGER'[user_id] ),
	///     'GAMMA - POSTERINGER'[account_number] = "K-3-12-1"
	/// ) + 0
	measure MEDLEMSBETALINGER =
			CALCULATE (
			    DISTINCTCOUNTNOBLANK ( 'GAMMA - POSTERINGER'[user_id] ),
			    'GAMMA - POSTERINGER'[account_number] = "K-3-12-1"
			) + 0
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: eadda3bb-6889-4c19-8377-e11405ed2de1
		dataCategory: true

	/// TOTALYTD(
	///     [MEDLEMSBETALINGER],
	///     'DEFAULT DATA - DATE VIEW'[date_actual]
	/// )
	measure 'MEDLEMSBETALINGER YTD' =
			TOTALYTD(
			    [MEDLEMSBETALINGER],
			    'DEFAULT DATA - DATE VIEW'[date_actual]
			)
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: c0ba5bd3-1eee-4d20-922e-6a2378c0da23
		dataCategory: true

	/// CALCULATE(
	///         [MEDLEMSBETALINGER],
	///         SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
	///     )
	measure 'MEDLEMSBETALINGER - SPLY' =
			CALCULATE(
			        [MEDLEMSBETALINGER],
			        SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
			    )
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: a08b154d-4494-4686-a4c8-becdc05d3955
		dataCategory: true

	/// TOTALYTD(
	///     [MEDLEMSBETALINGER YTD],
	///     SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
	/// )
	measure 'MEDLEMSBETALINGER YTD - SPLY' =
			TOTALYTD(
			    [MEDLEMSBETALINGER YTD],
			    SAMEPERIODLASTYEAR('DEFAULT DATA - DATE VIEW'[date_actual])
			)
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: 6a01c815-2b1e-40f9-a028-4328ad6cc737
		dataCategory: true

	/// CALCULATE([MEDLEMSBETALINGER],'GAMMA - POSTERINGER'[member_context]="NEW OR RELIVE")
	measure 'NEW_REWON MEMBERS' = CALCULATE([MEDLEMSBETALINGER],'GAMMA - POSTERINGER'[member_context]="NEW OR RELIVE")
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: 3848e83a-d292-4c26-a9c9-f7a353b05541
		dataCategory: true

	/// TOTALYTD(
	///     [NEW_REWON MEMBERS],
	///     'DEFAULT DATA - DATE VIEW'[date_actual]
	/// )
	measure 'NEW_REWON MEMBERS - YTD' =
			TOTALYTD(
			    [NEW_REWON MEMBERS],
			    'DEFAULT DATA - DATE VIEW'[date_actual]
			)
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: 09eb1200-43bc-44bd-91ac-d0ceab58c3f7
		dataCategory: true

	/// CALCULATE([MEDLEMSBETALINGER],'GAMMA - POSTERINGER'[member_context]="RESIGNING")
	measure RESIGNING_MEMBERS = CALCULATE([MEDLEMSBETALINGER],'GAMMA - POSTERINGER'[member_context]="RESIGNING")
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: 3c7f163d-815a-4b0c-b985-25cc48e5fef9
		dataCategory: true

	/// TOTALYTD(
	///     [RESIGNING_MEMBERS],
	///     'DEFAULT DATA - DATE VIEW'[date_actual]
	/// )
	measure 'RESIGNING_MEMBERS - YTD' =
			TOTALYTD(
			    [RESIGNING_MEMBERS],
			    'DEFAULT DATA - DATE VIEW'[date_actual]
			)
		formatString: #,0
		displayFolder: KPI \ MEDLEMMER
		lineageTag: c386845d-db4e-4d94-a307-e03db2e97200
		dataCategory: true

	column DoNotUse
		isHidden
		lineageTag: ba99afcc-a2df-4a18-97fa-6ccb0e3eac6e
		isNameInferred
		sourceColumn: [DoNotUse]

	partition '_MEASURES - CUSTOM' = calculated
		mode: import
		source = SELECTCOLUMNS({}, "DoNotUse", 1)

